bot: "triage"
csvHeader: "Currency,Currency spent,Currency Received,Profit"
exchange:
  exchange: "livecoin"
  keyFile: "keys/livecoin.key"
  fee: "0.0018"
  minOrder: "0.00666"
mock: true # če je true, pomeni da bot bot ne izvede dejanskih tradov
secondsToSleep: 30 # sekunde, ki jih bot prespi, potem ko se zaključi en bot tick
secondsToSleepAfterTrade: 30 # sekunde, ki jih bot prespi, potem ko se zaključi en bot tick
millisecondsBetweenOrders: 150 # milisekunde, ki jih bot počaka med tremi orderji
tradeSafety: "0.985" # nastavi na "1", če hočeš to ignorirat
qtyMaxDecimals: 8 # število decimalk na katero se zaokroži trading quantity
